### ISSUE TITLE
packagekit dbus api returns resolve signals in triplicate

### ISSUE THREAD

**Issue by purpleidea** [hughsie/PackageKit#112]
Strangely, packagekit seems to reply to the resolve method in triplicate!
Strangely, packagekit seems to reply to the resolve method in triplicate!
Strangely, packagekit seems to reply to the resolve method in triplicate!

okay, maybe my joke above isn't funny, but this is the case. If I resolve for ['powertop', 'sl'], I get signal output:

```
[1 sl;5.02-2.fc23;x86_64;installed:@commandline Joke command for when you type 'sl' instead of 'ls']
[1 sl;5.02-2.fc23;x86_64;installed:@commandline Joke command for when you type 'sl' instead of 'ls']
[1 sl;5.02-2.fc23;x86_64;installed:@commandline Joke command for when you type 'sl' instead of 'ls']
[2 powertop;2.8-1.fc23;x86_64;updates Power consumption monitor]
[2 powertop;2.8-1.fc23;x86_64;updates Power consumption monitor]
[2 powertop;2.8-1.fc23;x86_64;updates Power consumption monitor]
[2 powertop;2.7-6.fc23;x86_64;fedora Power consumption monitor]
[2 powertop;2.7-6.fc23;x86_64;fedora Power consumption monitor]
[2 powertop;2.7-6.fc23;x86_64;fedora Power consumption monitor]
Finished
Finished
Finished
```

It's not particularly disastrous because I can just discard duplicates, but still can be an issue nonetheless. I'm doing this with golang and the godbus library. I can provide reproducing code if it's not obvious what the issue is to the upstream.

Cheers

**Comment by ximion** [comment]
Which backend are you using?

**Comment by purpleidea** [comment]
@ximion this is running on Fedora 23, presumably using the DNF (libhif?) backend.

**Comment by hughsie** [comment]
Does `pkmon` also have the duplicate signals/ I'd be surprised if this was a PK bug as 3 finished signals to a client would cause untold misery. Could you perhaps be connecting to the signal handler multiple times?

**Comment by purpleidea** [comment]
@hughsie In the end I think this might be my fault. I was calling:
```
call := bus.BusObject().Call(dbusAddMatch, 0, "type='signal',path='"+ path +"',interface='"+ iface +"',member='"+signal+"'")
```
every time I wanted to add a new signal, and I was doing it three times. Switching that for:

```
foo := bus.BusObject()
for _, signal := range signals {
	foo.Call(dbusAddMatch, 0, "type='signal',path='"+ path +"',interface='"+ iface +"',member='"+signal+"'")
}
```
Seems to reduce things back to expected. I have no idea why that's the case, but if anything it's a bug in the dbus library, or its user, not packagekit afaict.

I've attached my golang "hacking code" here, which should really not be used anywhere, but to reproduce if anyone is curious. I'm about 50% through writing a somewhat proper golang library for packagekit which should be used instead.

I'll publish it as soon as it's ready, probably within https://github.com/purpleidea/mgmt/ until someone really wants it split out.

Thanks!

**Comment by purpleidea** [comment]
Apparently github doesn't allow uploading of golang files, so here they are:
https://paste.fedoraproject.org/323606/56413101/

Cheers!
