### ISSUE TITLE
InstallProvideFiles question

### ISSUE THREAD

**Issue by manisandro** [hughsie/PackageKit#115]
Sorry for abusing tickets to ask a question but:

I've been using InstallProvideFiles for many years in gImageReader, but I've gradually seen the documentation for the method disappear. Is that method deprecated (if so, what should be used instead?), and if not, is there a reason why it is so hidden?

Thanks

**Comment by hughsie** [comment]
Not deprecated; we just moved the implementation from gnome-packagekit to gnome-software.

**Comment by manisandro** [comment]
Okay thanks.
