### ISSUE TITLE
Backend :: ALPM :: Add support for "Usage" key in config file

### ISSUE THREAD

**Issue by lots0logs** [hughsie/PackageKit#122]
The Usage key was added to the default [config file](https://www.archlinux.org/pacman/pacman.conf.5.html#_repository_sections) in pacman v4.2. PackageKit currently crashes when the key is found in the config file. Pull request incoming....

**Comment by aleixpol** [comment]
This patch is just introducing format changes in many places, can you clean it to the actual `Usage` part?

**Comment by lots0logs** [comment]
@aleixpol Sorry for the delay! I realized that the backend does not need to handle the `Usage` for repos as alpm will take care of it by itself. The branch in the PR has been updated to simply ignore the `Usage` key instead of raising a fatal error. Let me know if its okay. Cheers!

**Comment by lots0logs** [comment]
@aleixpol Please see #131
