### ISSUE TITLE
Can't call Daemon::getTimeSinceAction successfully

### ISSUE THREAD

**Issue by aleixpol** [hughsie/PackageKit#124]
When calling `PackageKit::Daemon::global()->getTimeSinceAction(PackageKit::Transaction::RoleGetUpdates)` I get the following error message in Ubuntu 16.04.

```
org.freedesktop.DBus.Error.UnknownMethod", "Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: GetTimeSinceAction is not a valid method of interface org.freedesktop.PackageKit
```

**Comment by dantti** [comment]
I think this is because Ubuntu 16.04 uses a very old Packagekit and your
pk-qt is too new...

2016-05-11 7:51 GMT-03:00 Aleix Pol <notifications@github.com>:

> When calling
> PackageKit::Daemon::global()->getTimeSinceAction(PackageKit::Transaction::RoleGetUpdates)
> I get the following error message in Ubuntu 16.04.
>
> org.freedesktop.DBus.Error.UnknownMethod", "Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
>     (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
>   File "/usr/lib/python3/dist-packages/dbus/service.py", line 246, in _method_lookup
>     raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
> dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: GetTimeSinceAction is not a valid method of interface org.freedesktop.PackageKit
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hughsie/PackageKit/issues/124>
>



-- 
Daniel Nicoletti

KDE Developer - http://dantti.wordpress.com

**Comment by ximion** [comment]
Yes, Ubuntu messed this one up, so this isn't really a bug in PK... It's rather an Ubuntu bug, and I continue to lobby (= nag) them to finally update their 3y old PK.

I suggest you try this on Debian Testing, which has a very recent PK and QPK - the issue shouldn't happen there.

**Comment by aleixpol** [comment]
Why would I try Debian Testing? I'm just trying to make sure the Kubuntu users get the right behavior.

**Comment by ximion** [comment]
There is nothing we can do upstream to make Ubuntu ship a valid combination of packages. Testing against Debian would at least make sure that there is nothing wrong with upstream code.
Ideally, Kubuntu should ship a PPA updating PackageKit - and maybe Ubuntu itself will finally update this for Yakkety.

**Comment by dantti** [comment]
You can also try an older pk-qt API, iirc the DBus signature changed was
string, now int, and the new pk-qt will use a new one.

2016-05-11 15:00 GMT-03:00 Matthias Klumpp <notifications@github.com>:

> There is nothing we can do upstream to make Ubuntu ship a valid
> combination of packages. Testing against Debian would at least make sure
> that there is nothing wrong with upstream code.
> Ideally, Kubuntu should ship a PPA updating PackageKit - and maybe Ubuntu
> itself will finally update this for Yakkety.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/hughsie/PackageKit/issues/124#issuecomment-218539727>
>



-- 
Daniel Nicoletti

KDE Developer - http://dantti.wordpress.com

**Comment by ximion** [comment]
Closing after a discussion with apol on IRC.
Being a downstream issue, there is nothing we can do about this upstream anyway.
