### ISSUE TITLE
Resolve query with a missing package fails completely

### ISSUE THREAD

**Issue by aleixpol** [hughsie/PackageKit#127]
In _Discover_ we used to resolve appstream packages when it's loaded, to initialize whether they're installed or not. This turned out to be a problem when archlinux appstream db started offering an asset whose packagename wasn't there. I'm unsure if it's a design decision in PackageKit or an implementation error in the ALPM backend.

Here's how to test:
```
$ pkcon resolve vlc gcc
Resolving                     [=========================]         
Installed       gcc-6.1.1-1.x86_64 (installed)                                  The GNU Compiler Collection - C and C++ frontends
Installed       vlc-2.2.3-3.x86_64 (installed)                                  A multi-platform MPEG, VCD/DVD, and DivX player
$ pkcon resolve vlc gcc wrong
Resolving                     [=========================]         
Fatal error: wrong: could not find or read package
```

**Comment by hughsie** [comment]
Looks like a backend problem to me:

$ pkcon resolve gcc wrong
Resolving                     [=========================]         
Installed   	gcc-6.1.1-2.fc24.x86_64 (installed:fedora)                  	Various compilers (C, C++, Objective-C, Java, ...)

the resolve method is perfect for finding out if a package exists.
