### ISSUE TITLE
ax_cxx_compile_stdcxx macros

### ISSUE THREAD

**Issue by belka-ew** [hughsie/PackageKit#144]
Could we include:
- ax_cxx_compile_stdcxx_11 and ax_cxx_compile_stdcxx_14
or
- ax_cxx_compile_stdcxx.m4

macros into /m4? They are used by c++ backends and seem not to be in the standard autoconf distribution. I'm for the second macro (ax_cxx_compile_stdcxx.m4) but it would require existing C++ backends use:
```
AX_CXX_COMPILE_STDXX([11], [ext], [mandatory])
```
instead of
```
AX_CXX_COMPILE_STDXX_11([ext], [mandatory])
```
And I don't know if the maintainers of aptcc and nix like it.

Ping @hughsie, @matthewbauer, @ximion

**Comment by belka-ew** [comment]
To make the problem more clear.
If I clone the PackageKit repository and hit:
```shell
sh autogen.sh
```

I get an error:
./configure: line 22225: syntax error near unexpected token `ext,'
./configure: line 22225: `	AX_CXX_COMPILE_STDCXX_11(ext, mandatory)'

It is because the two macros you see in the pull request #146 are missing in Slackware (and in the default autoconf/autotools package which one is pretty old), but available in autoconf-archive: https://www.gnu.org/software/autoconf-archive/The-Macros.html#The-Macros
I suppose this error doesn't happen in Debian/Ubuntu because these macros are shipped by another package.

I see two solutions:
- I could also create an extra package with additional macros for Slackware (in this case I just close this issue and the last pull request of me).
- But I want to ask whether it would be possible just to include them in PackageKit, since I don't see them used anywhere else (the pull request I created would do everything needed).

The second option would be just simpler for me.
Is it OK?
Thanks :)

**Comment by hughsie** [comment]
So, it would be good to find out why exactly this fails on slackware; it would be much easier to just upgrade autoconf for example.

**Comment by kalev** [comment]
I agree, I think it would make sense for slackware to just update autoconf-archive which has the macro.

**Comment by kalev** [comment]
http://www.gnu.org/software/autoconf-archive/

**Comment by belka-ew** [comment]
Ok, then let us do it.
Sorry for a lot of noise )
