### ISSUE TITLE
alpm: pacman updates are not tracked

### ISSUE THREAD

**Issue by fbourigault** [hughsie/PackageKit#15]
From Jan de Groot :
> System updates by pacman are not tracked, after running pacman –Syu packageKit will not see that updates are already installed

From kalev :
> the plan is to set up a file monitor on the package database file and use it to remove the prepared updates if anything external touches the database

The alpm local database is a directory tree. Here is the structure :
```
/var/lib/pacman/local/
├── aalib-1.4rc5-10
│   ├── desc
│   ├── files
│   ├── install
│   └── mtree
├── accountsservice-0.6.38-1
│   ├── desc
│   ├── files
│   └── mtree
├── acl-2.2.52-2
│   ├── desc
│   ├── files
│   └── mtree
├── alsa-lib-1.0.28-1
│   ├── desc
│   ├── files
│   └── mtree
├── alsa-plugins-1.0.28-2
│   ├── desc
...
```
Watching the `/var/lib/pacman/local/` directory for changes should be enough.

As this will be implemented in the backend code, I'm waiting for the Hif implementation and then will do the alpm one.

**Comment by fbourigault** [comment]
Hif implementation : 2b7db3423ec96b65f1b5fe4d5b89335813313a64

I will try to do this soon

**Comment by fbourigault** [comment]
In which case I need to invalidate the database ? I think change in the local db (i.e Package was installed/upgraded/downgraded/re-installed/removed). Does I also need to watch for repos package list refresh ? And did I missed an other case ? cc @kalev @hughsie

**Comment by aleixpol** [comment]
Confirmed.

**Comment by hughsie** [comment]
The hif backend inhibits just before it does any action on the package database, and then uninhibits when it's done. This means that any invalidation calls that get triggered get ignored (otherwise, PackageKit does the modification, then notifies itself that it did the action).

**Comment by fbourigault** [comment]
Reopening because I probably wrote a bad implementation.

**Comment by fbourigault** [comment]
I think the local db pkgcache need to be invalidated too. I asked pacman-dev mailing list to know how can I do. https://lists.archlinux.org/pipermail/pacman-dev/2015-March/019997.html
