### ISSUE TITLE
[aptcc] updates always installs with fromuser=true

### ISSUE THREAD

**Issue by apachelogger** [hughsie/PackageKit#151]
when updating a package it runs through
`AptCacheFile::tryToInstall`
which calls
`    GetDepCache()->MarkInstall(Pkg, false);`
which ultimately has this signature
```
   bool MarkInstall(PkgIterator const &Pkg,bool AutoInst = true,
		    unsigned long Depth = 0, bool FromUser = true,
		    bool ForceImportantDeps = false);
```
which IIRC means that every package ever looses its `pkgCache::Flag::Auto` which means apt won't suggest it be removed if all it's dependees were removed. Namely aptcc defuncts the entire `pkgCache::Flag::Auto` use-case

Should be something like
```
/***************************************************************************
 *   Copyright © 2010-2012 Jonathan Thomas <echidnaman@kubuntu.org>        *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or         *
 *   modify it under the terms of the GNU General Public License as        *
 *   published by the Free Software Foundation; either version 2 of        *
 *   the License or (at your option) version 3 or any later version        *
 *   accepted by the membership of KDE e.V. (or its successor approved     *
 *   by the membership of KDE e.V.), which shall act as a proxy            *
 *   defined in Section 14 of version 3 of the license.                    *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>. *
 ***************************************************************************/
            bool fromUser = !(State.Flags & pkgCache::Flag::Auto);
            (*m_cache)->MarkInstall(iter, true, 0, fromUser);
```

**Comment by dantti** [comment]
hmm interesting, I wonder if there is some case like apt install foo that we might want to remove the auto flag

**Comment by dantti** [comment]
Does this change the recommends in anyway? I hadn't have time to have a closer look into that.

**Comment by apachelogger** [comment]
It doesn't. Basically what fromUser=true does is equal to `apt-mark manual $pkg`, conversely preserving fromUser as either true/false depending on `pkgCache::Flag::Auto` is effectively no-change (i.e. the flag is kept), fromUser=false is equal to `apt-mark auto $pkg` (i.e. explicitly marking the package as auto-installed)

Whether or not recommends get installed is a decision that happens in the resolver and is independent of auto. Auto basically just reflects whether or not the package was installed as part of automatic dependency resolution or was explicitly requested by the user.

**Comment by apachelogger** [comment]
I kind of have a fix for this. Fairly straight forward, just needs us to mark the iter protected in the resolver after marking. Why is it being protected before marking anyway? That only restricts the amount of work the resolver can do to help us install the thing...
