### ISSUE TITLE
[aptcc] updates never get autoinst resolution

### ISSUE THREAD

**Issue by apachelogger** [hughsie/PackageKit#153]
updates call `AptCacheFile::tryToInstall` which calls `GetDepCache()->MarkInstall(Pkg, false);` which never ever manages to resolve involved problems since this explicitly sets autoinst=false BUT then never lets the resolver attempt to resolve this by setting autoinst. Notably what happens is that apt-pkg will then have all packages marked for install, but not be able to remove (and probably install new) packages which would be in conflict with the now strictly marked packages.

Example:

- A installed, A depends B
- B installed, new B available, conflicts C
- C is installed and has an upgrade
- Updating A, B, and C
 - A marked, B marked, C marked
 - A gets resolved by installing B, C can't be resolved because we explicitly want C and explicitly want A and explicitly want B but A through B conflicts C, B directly conflicts C. We can't resolve this by removing C because C was explicitly marked as noautoinst.

What should happen is:

- run through intended changes ⇒ mark everything install autoinst=false
- run through intended changes AGAIN ⇒ mark everything install autoinst=true
- at this point packages will be marked for remove ⇒ depending on policy mark removed packages as keep to prevent them from actually getting removed (which I think is actually incompatible with packagekit api, so this behavior probably makes no sense)
 - resolveByKeep (as mentioned, I think upgrade-by-not-removing-anything isn't really a thing that should be supported)

**Comment by apachelogger** [comment]
FWIW this might actually be the root cause of #145

**Comment by dantti** [comment]
That why I asked in #151 ... will try to take a look as soon as I finish a new Cutelyst release.
