### ISSUE TITLE
Package download failure

### ISSUE THREAD

**Issue by mcatanzaro** [hughsie/PackageKit#157]
I'm using PackageKit-1.1.3-2.fc24. I clicked the Update button in GNOME Software while pkmon was running in the background. The spinner ran for a while, then, although the computer had not been updated in months, GNOME Software reported that the computer was all up to date, displayed a big checkmark, and showed the time I clicked the updates button as the last check for updates, as if everything was successful. But I had pkmon running in the background, where I saw this:

`459_ecbdaaea error code: internal-error, cannot download l/libinput-devel-1.4.1-1.fc24.x86_64.rpm to /var/cache/PackageKit/24/metadata/updates/packages/: Curl error (42): Operation was aborted by an application callback for http://mirror.math.princeton.edu/pub/fedora/linux/updates/24/x86_64/l/libinput-devel-1.4.1-1.fc24.x86_64.rpm [Callback aborted]`

Unfortunately I don't have more of the log, but I guess none of it was interesting or I would have saved it. The error does not seem to be reproducible.

**Comment by Conan-Kudo** [comment]
I haven't seen this issue across any usage of PackageKit with the DNF backend recently (in the last couple of years)...
