### ISSUE TITLE
UpdatesChanged is not emitted when available updates list changes

### ISSUE THREAD

**Issue by antonio-rojas** [hughsie/PackageKit#169]
When the available updates list changes (eg. by running 'pkcon get-updates' when new updates are available) the UpdatesChanged signal is not emitted. This breaks update notifiers that rely on this signal (such as Plasma Discover).
This affects the alpm backend, I haven't tested other backends.

**Comment by aleixpol** [comment]
I can reproduce this. Also with aptcc as well

**Comment by Appadeia** [comment]
This issue should be closed since the fix is merged. Wonder why GitHub didn't pick up the mention as a "will close this issue" mention.

**Comment by aleixpol** [comment]
I'd say it's fixed too for aptcc now, at least our users are getting the updates notifications. I'd say let's just close it for now.
