### ISSUE TITLE
[ALPM] itemProgress reported for unknown packages

### ISSUE THREAD

**Issue by aleixpol** [hughsie/PackageKit#173]
As reported by `pkmon`:
```
/1211_bddeabcc  item-progress ,80 [unknown]
```

On PackageKitQt::Transaction::itemChanged I get a "" empty string itemID.

**Comment by Appadeia** [comment]
libalpm intentionally triggers the progress callback without a package name for various things. Not sure whether it would be more desirable to ignore these callbacks downstream or add extra information to these callbacks upstream.

**Comment by Appadeia** [comment]
After consulting with an Arch developer, the desirable course of action would be to interpret these callbacks with blank names as being for the transaction in general and react accordingly.
