### ISSUE TITLE
Remove older packages from cache as newer ones come in

### ISSUE THREAD

**Issue by mattdm** [hughsie/PackageKit#194]
See [Fedora bug 1306992](https://bugzilla.redhat.com/show_bug.cgi?id=1306992). Basically, when people delay applying updates, older rpms accumulate, and then when the newer updates are installed, the older packages linger.

This has been nominated as a potential high-priority bug for Fedora — it doesn't violate release criteria, but affects a lot of people. We definitely appreciate any attention you can give to it. Thank you!

**Comment by mattdm** [comment]
Any further thoughts on this? Reports of problems continue to come in in the Fedora bug.

**Comment by kalev** [comment]
This should now be fixed in https://github.com/hughsie/PackageKit/commit/66f2966fb6484a86324f98302659c5f27a02b1b5
