### ISSUE TITLE
DNF backend limited to hardcoded set of repository names

### ISSUE THREAD

**Issue by da2x** [hughsie/PackageKit#198]
The DNF backend for Fedora is for some inexplicit reason [hardocded to only accept some repository names](https://github.com/hughsie/PackageKit/blob/7efa7b408aec8c00162ae23dcf7f65e314460617/backends/dnf/dnf-backend-vendor-fedora.c#L28-L39). This means PackageKit can’t be used to install or update packages from an external repository.

As far as I can tell, this limitation doesn’t apply to any other backend except DNF. The limitation isn’t even user configurable.

The list doesn’t even include the [`fedora-cisco-openh264` repository](https://fedoraproject.org/wiki/OpenH264) which is included by default on Fedora Workstation 25 and later. The [EPEL repository](https://fedoraproject.org/wiki/EPEL) also isn’t present.

I’ve installed the [Vivaldi browser repository](http://repo.vivaldi.com/archive/rpm/x86_64) in `/etc/yum.repo.d/vvialdi.repo`. `dnf search vivaldi` finds the package as expected but `pkcon search vivaldi` doesn’t find anything as it’s unaware of it’s repository.

**Update:** I can find the package with `pkcon install vivaldi-stable`, but I can’t find it with `pkcon search vivaldi` or `pkcon search vivaldi-stable`. `pkcon search Vivaldi` works, but the package’s full name is `vivaldi-stable-1.10.867.42-1.x86_64` in all lowercase. Not sure what the issue is here.

Why is this limitation in place only for DNF? Please remove it _or make it configurable_ so the DNF backend can be used on add-on repositories just as the other backends already support.

**Comment by hughsie** [comment]
"supported" in PackageKit parlance means "supported by the OS vendor" rather than "can install from".

**Comment by Conan-Kudo** [comment]
PR submitted to add `fedora-cisco-openh264` as a supported repo: https://github.com/hughsie/PackageKit/pull/203

**Comment by Conan-Kudo** [comment]
@da2x PackageKit with the dnf backend can and does support any and all repositories in `/etc/yum.repos.d`. However, `pkcon search` is kind of dumb compared to `dnf search`, so YMMV on actually identifying packages.

Looking at the code in `backends/dnf/pk-backend-dnf.c`, I don't see anything in particular that restricts search to only supported repos, unless I'm missing something, @hughsie?

**Comment by AsciiWolf** [comment]
Not sure if that bug is related to this issue, but openh264 still cannot be installed using GNOME Software on Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1440331

**Comment by kalev** [comment]
Let's close this, I believe "supported" is working as designed here.
