### ISSUE TITLE
Can't build PackageKit on without vapigen

### ISSUE THREAD

**Issue by aleixpol** [hughsie/PackageKit#216]
I get the following error message:
```
lib/packagekit-glib2/Makefile.am:275: error: ENABLE_VAPIGEN does not appear in AM_CONDITIONAL
```
Looking into the code it looks it's supported, automake code is just not dealing with it.

I even tried passing `--enable-introspection=no` but since it's just checking `HAVE_INTROSPECTION` it still goes through.

**Comment by robert-ancell** [comment]
Fixed in 3a0d40174b7014b66964e3bfebb276633a5bac8e. Thanks!
