### ISSUE TITLE
Installing software from a newly added repository does not work on Fedora

### ISSUE THREAD

**Issue by AsciiWolf** [hughsie/PackageKit#217]
If an user adds any new repository on Fedora, for example RPM Fusion, and then tries to install some software that is present in the repository using GNOME Software, he gets a "Enable Third-Party Software Source?" dialog, however clicking on "Enable and Install" does nothing, leaving the user without any possibility to install the third-party software in a user friendly way. This also includes no user-friendly way of installing codecs or NVIDIA drivers.

Not sure if this bug happens only on Fedora or also on other distributions, but I think this bug is maybe a bug in PackageKit, rather than in GNOME Software.

Here is a link of the original bug report and more information from Christophe Fergeau:
https://bugzilla.redhat.com/show_bug.cgi?id=1478991
https://bugzilla.gnome.org/show_bug.cgi?id=786038#c1

**Comment by AsciiWolf** [comment]
Still an issue on Fedora 27, but it is now possible to click on the "Enable and Install" button. However, clicking the button displays a "repo already enabled" error message and installation is aborted.

**Comment by AsciiWolf** [comment]
Any news regarding this issue?

**Comment by hughsie** [comment]
No news. Could you debug the issue a bit and try to work out what is wrong please? I'm scheduled to work on other things for the rest of this week.

**Comment by AsciiWolf** [comment]
@hughsie I have already tried to debug the issue, but I was not able to get more information than [Christophe Fergeau](https://bugzilla.gnome.org/show_bug.cgi?id=786038#c1).

**Comment by AsciiWolf** [comment]
It looks like it is now [partially fixed](https://bugzilla.redhat.com/show_bug.cgi?id=1478991#c3) in Fedora 27.

**Comment by AsciiWolf** [comment]
It looks like that this issue has been fixed in Fedora 27, except for H.264 ([#1440331](https://bugzilla.redhat.com/show_bug.cgi?id=1440331)) which is probably a different issue.
