### ISSUE TITLE
Raw Dbus documentation

### ISSUE THREAD

**Issue by sotiris-oikonomou** [hughsie/PackageKit#220]
Hello,

Is there any complete raw dbus documentation (except https://www.freedesktop.org/software/PackageKit/gtk-doc) that explains the Methods and their possible parameters. For example: In org.freedesktop.PackageKit.Transaction the GetUpdates() method expects a "A correct filter bitfield". What are the possible values here, how do I find them, or the same with method GetRepoList(), or with SetHints(), what are the possible hints to be set. I am trying to use PackageKit via python and I cannot seem to find those details.

**Comment by hughsie** [comment]
They're all specified in https://github.com/hughsie/PackageKit/blob/master/lib/packagekit-glib2/pk-enum.h#L281

**Comment by sotiris-oikonomou** [comment]
Thank you.
