### ISSUE TITLE
Flatpak runtimes are not fully installed or updated when using GNOME Software

### ISSUE THREAD

**Issue by AsciiWolf** [hughsie/PackageKit#226]
Not sure if this is a PackageKit or GNOME Software issue. (I have also [reported](https://bugzilla.gnome.org/show_bug.cgi?id=788363) it in GNOME BZ.) If you try to install any Flatpak application that requires GNOME or another runtime to be installed (for example [OpenArena](https://flathub.org/repo/appstream/ws.openarena.OpenArena.flatpakref)), some parts of the runtime that are additional, but required by the application (for example org.freedesktop.Platform.GL.nvidia), are not installed when using GNOME Software. They are installed if you run "flatpak update" afterwards. The same issue is when updating existing runtimes using GNOME Software - the additional parts are not updated and must be updated manually by running "flatpak update".

**Comment by hughsie** [comment]
This has nothing to do with PackageKit. We'll debug in the GNOME bug.
