### ISSUE TITLE
Don't prepend "installed:" for installed apt and yum packages

### ISSUE THREAD

**Issue by Pointedstick** [hughsie/PackageKit#236]
## Issue ##

Right now PackageKit prepends "installed:" for installed apt and yum packages:
- https://github.com/hughsie/PackageKit/blob/master/backends/aptcc/apt-utils.cpp#L411
- https://github.com/hughsie/PackageKit/blob/master/backends/yum/yumBackend.py#L2565

The DNF backend also seems to expect it:
- https://github.com/hughsie/PackageKit/blob/master/backends/dnf/pk-backend-dnf.c#L1712

This seems like a case where the client should choose how it expresses that a package or app is already installed, rather than being limited to working within how PackageKit presents this data. To put it into MVC terminology, this is PackageKit acting as a model as well as a view, when it should act purely as a model and let the client be the view.

It also seems weird to only format the origin string this way for apt and yum, but not for zypp, pacman, portage, or any other backends.

## Real-world impact ##
I'm working a new view for KDE Discover, which consumes this data. I want to present information about what packages are installed in another way, so I'm currently having to manually remove "installed:" for installed packages because:

```
auto pkgid = availablePackageId();
QString pkOrigin = PackageKit::Daemon::packageData(pkgid);
return pkOrigin.remove("installed");
```

**Comment by ximion** [comment]
This is a package-id, which is a machine-readable string to uniquely identify a package. It has absolutely nothing to do with any user-facing representation. Frontends are expected to either pass it to PackageKit verbatim, or parse it with some of the provided functions.

The `data` block of a package-id is used to display its repository name or "installed" in case the package is locally installed. For packages that re locally installed from a repository, we use the `installed:<repo>` convention, which is perfectly legal.

You can read more on what a package-id is at https://www.freedesktop.org/software/PackageKit/gtk-doc/concepts.html#introduction-ideas-packageid and parse it using PKs API (see https://www.freedesktop.org/software/PackageKit/gtk-doc/PackageKit-pk-package-id.html ) - usually, you don't need to parse it though and just pass it back into a new call to PK after receiving it from another.

**Comment by Pointedstick** [comment]
Ah OK, thanks! Sorry for the noise.
