### ISSUE TITLE
Should remove unused dependencies (APT backend)

### ISSUE THREAD

**Issue by AsciiWolf** [hughsie/PackageKit#245]
Separate issue from #201 - aptcc backend has the same issue.

PackageKit aptcc backend does not support uninstallation of unused dependencies. This is a major issue for regular users, especially since GNOME Software does not report when installing a desktop environment or another big dependency with an application and there is no easy way for regular user to remove the unused dependencies after uninstalling the application. Please, consider fixing this.

**Comment by robert-ancell** [comment]
See #253

**Comment by robert-ancell** [comment]
Ubuntu bug https://launchpad.net/bugs/1552792

**Comment by AsciiWolf** [comment]
Autoremove is now supported by the aptcc backend!
