### ISSUE TITLE
pk-offline-update failed with std::runtime_error, caused hang

### ISSUE THREAD

**Issue by mrjohnson22** [hughsie/PackageKit#291]
- Fedora 29
- PackageKit-1.1.11-1.fc29.x86_64
- gnome-software-3.30.5-1.fc29.x86_64

Recently, I had an offline update get stuck at 97%. Judging from the messages on the boot screen, it looked like pk-offline-update and/or packagekitd hit a fatal error:

`packagekitd: terminate called after throwing an instance of 'std::runtime_error'`

I was still able to log in as root in a VT, where I was able to run `shutdown now` instead of having to press the power button to get out of the hang, and upon reboot everything seemed fine.

The offline updated was launched from Gnome Software's "Restart and Install" button.

Attached is an excerpt of my journal that has messages related to the apparent crash.

[pkconMessages.txt](https://github.com/hughsie/PackageKit/files/2568181/pkconMessages.txt)

**Comment by kalev** [comment]
This was an issue with libdnf crashing that got fixed yesterday: https://bugzilla.redhat.com/show_bug.cgi?id=1642796
