### ISSUE TITLE
segmentation fault in init

### ISSUE THREAD

**Issue by d10r** [hughsie/PackageKit#298]
I'm running stock Ubuntu 18.04. Yesterday, my machine could barely boot, because several services failed to start.  

I could start all other failing services (e.g. NetworkManager, polkit, ...) manually, but can't do so with PackageKit:
```
# /usr/lib/packagekit/packagekitd -v
11:39:01        PackageKit          Verbose debugging enabled (on console 1)
11:39:01        PackageKit          daemon shutdown set to 0 seconds
11:39:01        PackageKit          clearing download cache at /var/cache/PackageKit/downloads
Segmentation fault (core dumped)
```

```
# /usr/lib/packagekit/packagekitd --version
Version 1.1.9
```

Already tried to downgrade it to a previous version (as it was recently updated), but didn't make a difference.

I'm willed to build it from source myself in order to figure out where exactly it fails. But couldn't yet figure out how to build it. I've done some C development about 15 years ago, but am not familiar with nowadays build toolchains for C projects. Already tried `make` and `automake`, both fail. Hints welcome.

**Comment by hughsie** [comment]
Can you get a backtrace please?

**Comment by d10r** [comment]
For the record (and probably for entertainment):
after locating the location in libc, I still didn't understand the source of the problem.  
2 days later I had the idea to run with `strace`. This showed that the last file opened before the segmentation fault was `/etc/passwd`. So I did a very close look at it - and noticed that the first 2 entries were missing: `root` and `daemon`.  
I suspect that was an accident with vim (like: typing something while not in edit mode).

Sorry for bothering you.

**Comment by kalev** [comment]
Glad you figured it out :)
