### ISSUE TITLE
packagekitd crashes when GNOME Software is launching on debian buster

### ISSUE THREAD

**Issue by ahayzen** [hughsie/PackageKit#314]
# What happened

When launching GNOME Software it hangs at "Software catalog is being loaded", upon investigation we found that packagekitd is crashing (previous discussions here https://gitlab.gnome.org/GNOME/gnome-software/issues/589 ).

# Logs

Journalctl shows the following information when this occurs

```
Feb 13 21:57:26 andrew-pc dbus-daemon[378]: [system] Activating via systemd: service name='org.freedesktop.PackageKit' unit='packagekit.service' requested by ':1.105' (uid=1000 pid=1572 comm="gnome-software --verbose ")
Feb 13 21:57:26 andrew-pc systemd[1]: Starting PackageKit Daemon...
Feb 13 21:57:26 andrew-pc PackageKit[1578]: daemon start
Feb 13 21:57:26 andrew-pc dbus-daemon[378]: [system] Successfully activated service 'org.freedesktop.PackageKit'
Feb 13 21:57:26 andrew-pc systemd[1]: Started PackageKit Daemon.
Feb 13 21:57:26 andrew-pc PackageKit[1578]: uid 1000 is trying to obtain org.freedesktop.packagekit.system-sources-refresh auth (only_trusted:0)
Feb 13 21:57:26 andrew-pc PackageKit[1578]: uid 1000 obtained auth for org.freedesktop.packagekit.system-sources-refresh
Feb 13 21:57:26 andrew-pc gnome-shell[865]: clutter_input_focus_set_cursor_location: assertion 'clutter_input_focus_is_focused (focus)' failed
Feb 13 21:57:27 andrew-pc packagekitd[1578]: terminate called after throwing an instance of 'std::length_error'
Feb 13 21:57:27 andrew-pc packagekitd[1578]:   what():  basic_string::_M_replace
Feb 13 21:57:27 andrew-pc systemd[1]: packagekit.service: Main process exited, code=killed, status=6/ABRT
Feb 13 21:57:27 andrew-pc systemd[1]: packagekit.service: Failed with result 'signal'.
```

Running packagekitd under gdb gives the following backtrace https://pastebin.ubuntu.com/p/zd4YRfgzZn/

# Versions

```
$ lsb_release -rd
Description:	Debian GNU/Linux buster/sid
Release:	testing
$ apt-cache policy gnome-software
gnome-software:
  Installed: 3.30.6-4
  Candidate: 3.30.6-4
  Version table:
 *** 3.30.6-4 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
$ apt-cache policy packagekit
packagekit:
  Installed: 1.1.12-1
  Candidate: 1.1.12-1
  Version table:
 *** 1.1.12-1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by hughsie** [comment]
@dantti -- do you know the point of contact for the aptcc backend is now? Thanks.

**Comment by dantti** [comment]
Well it's me, @ximion and @julian-klode . Regarding this crash I could not see the issue by the BT besides PK having a bunch of threads which is a bit suspect...

**Comment by julian-klode** [comment]
Well, duh, the backtrace is from an entirely different thing - a signal `Thread 4 "pool" received signal SIG33, Real-time event 33.`

**Comment by ahayzen** [comment]
Ah I didn't spot this trace was different, sorry.

Hmm, is anyone else able to reproduce this issue ? It happens on Debian Buster sometimes at startup you can see the `packagekitd` crash in `journalctl`, and then `gnome-software` will hang on launch. If it doesn't happen, stopping `gnome-software` and trying to start your own instance will usually cause it. I spoke with folks on `#debian-gnome` and they said they had seen `gnome-software` sometimes hanging as well.

Or does anyone have any suggestions how to catch a correct trace? I tried installing `systemd-coredumpctl` but that doesn't seem to capture anything (maybe it isn't configured correctly), and as shown above manually starting `packagekitd` seems to result in a different trace :-/

**Comment by ahayzen** [comment]
FWIW this does seem to be happening for multiple people in Debian Buster, I have found some Debian bugs https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917812 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922236 which are describing this issue.

**Comment by ahayzen** [comment]
So running `packagekitd` directly (not with gdb) fails with the `throwing an instance of 'std::length_error'`, this is `packagekitd --verbose` https://pastebin.ubuntu.com/p/n3s9N4w88z/   and this is `strace packagekitd --verbose` https://pastebin.ubuntu.com/p/bGJTyyfVs7/  not sure if they help narrow what it might be doing around the time of the crash.

**Comment by nroach44** [comment]
I thought I'd jump on here too - `apt-get remove --purge packagekit && apt-get install gnome-software` will fix the issue temporarily

**Comment by nroach44** [comment]
I have strace logs of the crashes:
https://nroach44.id.au/917812_pkit_strace.txt
https://nroach44.id.au/917812_gsoft_strace.txt

PKit trace should show GS accessing it normally twice, and then I killed GS, and started the GS trace, where PK crashes. I then kill GS before the log gets too much larger. From what I can tell, unlike the GDB logs, this crashes in the same fashion.

Hopefully this helps.

**Comment by ahayzen** [comment]
An interesting further data point is that building packagekit with aptcc with master I can *not* make it crash, but using https://github.com/hughsie/PackageKit/releases/tag/PACKAGEKIT_1_1_12 (which is what I believe Debian is using) I can.

Stepping through the commits I have found that if I apply https://github.com/hughsie/PackageKit/commit/d49e789cb9c3ab40afe9e1af3196022180391966 on top of 1.1.12 then it fixes the issue :-)

**Comment by ahayzen** [comment]
FYI I've submitted this https://salsa.debian.org/pkgutopia-team/packagekit/merge_requests/1 is anyone else able to confirm that this change fixes the issue for them ?

**Comment by Yvan-Masson** [comment]
@ahayzen Thanks for the patch, I confirm that it solved the issue for me.

Regards,
Yvan

**Comment by ahayzen** [comment]
Thanks for confirming!  Is anyone able to help get https://salsa.debian.org/pkgutopia-team/packagekit/merge_requests/1 into the buster release ?

**Comment by hughsie** [comment]
I can do a new upstream tarball release if it makes the process easier...

**Comment by jbicha** [comment]
Debian has accepted that patch into Unstable (it should land in Buster automatically after the minimum aging period.)

**Comment by ahayzen** [comment]
This has landed in Debian Buster, therefore I am going to close this issue.

**Comment by unclesamrocks** [comment]
same issue on popos 

trying `dpkg --configure -a` leads to `PackageKit daemon disappeared` error

```
dec 13 10:22:59 pop-os systemd[1]: Starting PackageKit Daemon...
dec 13 10:22:59 pop-os PackageKit[407889]: daemon start
dec 13 10:22:59 pop-os systemd[1]: Started PackageKit Daemon.
dec 13 10:22:59 pop-os PackageKit[407889]: uid 1000 is trying to obtain org.freedesktop.packagekit.system-update auth (only_trusted:1)
dec 13 10:22:59 pop-os PackageKit[407889]: new update-packages transaction /17984_dcecbbbb scheduled from uid 1000
dec 13 10:22:59 pop-os PackageKit[407889]: uid 1000 obtained auth for org.freedesktop.packagekit.system-update
dec 13 10:23:09 pop-os packagekitd[407889]: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. 
dec 13 10:23:09 pop-os PackageKit[407889]: update-packages transaction /17984_dcecbbbb from uid 1000 finished with failed after 10004ms
```

**Comment by sidt4** [comment]
Not sure how your issue is related to this 5 year closed bug. Can you clarify ?
