### ISSUE TITLE
Please drop the dependency on gtk+-2.0

### ISSUE THREAD

**Issue by zaitor** [hughsie/PackageKit#333]
If my quick check is correct, it seems that gtk+-2.0 dep was added for building the mozilla plugin that is long gone.

I did a hackpatch dropping gtk2, and it seems to work fine (not in upstreamable shape though).

**Comment by ximion** [comment]
FWIW, on Debian we don't ship the GTK+2 stuff anymore (mostly a plugin to find missing fonts) and only stick to the GTK+3 version of that module.

**Comment by hughsie** [comment]
I think all the GTK2 stuff could be removed indeed.

**Comment by Conan-Kudo** [comment]
This has been removed in git master as part of the transition to Meson.
