### ISSUE TITLE
gpk-update-viewer always fullscreen

### ISSUE THREAD

**Issue by oldnat** [hughsie/PackageKit#346]
Would it be possible that gpk-update-viewer does not start fullscreen? It is hard to handle it on a big monitor (and I have a big one). This ist not very problematic, but it would be nice if it would be possible. Thank you very much, Nat

**Comment by JonathanKang** [comment]
That's an issue of gnome-packagekit, not PackageKit. You can report your issue [here](https://gitlab.gnome.org/GNOME/gnome-packagekit).

**Comment by oldnat** [comment]
Thank you, I 'll do.
