### ISSUE TITLE
aptcc: gets stuck upon get-distro-upgrades

### ISSUE THREAD

**Issue by aleixpol** [hughsie/PackageKit#349]
I noticed because Discover issues the transaction, but I can easily reproduce with pkcon.

```
$ pkcon get-distro-upgrades 
Getting upgrades              [=========================]
Starting                      
```
Starting showing a bouncing cursor indefinitely.

This was tested on Ubuntu 19.10 with packagekit 1.1.12.

**Comment by aleixpol** [comment]
Tried running the daemon by hand, I get some more information:

```
$ G_MESSAGES_DEBUG=all sudo /usr/lib/packagekit/packagekitd  -v --keep-environment
15:28:25        PackageKit          Verbose debugging enabled (on console 1)
15:28:25        PackageKit          daemon shutdown set to 300 seconds
15:28:25        PackageKit          clearing download cache at /var/cache/PackageKit/downloads
15:28:25        PackageKit          setting config file watch on /etc/PackageKit/PackageKit.conf
15:28:25        PackageKit          Trying to load : aptcc
15:28:25        PackageKit          dlopening '/usr/lib/x86_64-linux-gnu/packagekit-backend/libpk_backend_aptcc.so'
15:28:25        PackageKit          trying to open database '/var/lib/PackageKit/transactions.db'
15:28:25        PackageKit          job count is now at 10532
15:28:25        PackageKit          PkEngine: acquired name: org.freedesktop.PackageKit
15:28:25        PackageKit          0 transactions in list, 0 committed but not finished
15:28:26        PackageKit          CreateTransaction method called
15:28:26        PackageKit          job count now 10533
15:28:26        PackageKit          trying to open database '/var/lib/PackageKit/transactions.db'
15:28:26        PackageKit          job count is now at 10532
15:28:26        PackageKit          transaction now new
15:28:26        PackageKit          setting sender to :1.163
15:28:26        PackageKit          adding transaction 0x55a8985bc210
15:28:26        PackageKit          sending object path: '/10533_dcdebebc'
15:28:26        PackageKit          notify::connected
15:28:26        PackageKit          SetHints method called: locale=en_US.UTF-8, background=false, interactive=true, cache-age=4294967295
15:28:26        PackageKit          locale changed to en_US.UTF-8
15:28:26        PackageKit          cache-age changed to 4294967295
15:28:26        PackageKit          GetDistroUpgrades method called
15:28:26        PackageKit          transaction now ready
15:28:26        PackageKit          changing transaction to exclusive mode
15:28:26        PackageKit          1 transactions in list, 1 committed but not finished
15:28:26        PackageKit          transaction now running
15:28:27        PackageKit          install uid now 1001
15:28:27        PackageKit          install cmdline now PackageKit: get-distro-upgrades
15:28:27        PackageKit          setting role for /10533_dcdebebc to get-distro-upgrades

(packagekitd:14918): PackageKit-CRITICAL **: 15:28:27.004: pk_backend_get_distro_upgrades: assertion 'backend->priv->desc->get_distro_upgrades != NULL' failed
Trace/breakpoint trap
```

**Comment by apachelogger** [comment]
Probably broken because the implementation was crippled in debian https://salsa.debian.org/pkgutopia-team/packagekit/commit/492f733891cd69e0e8c39ef6df827fa7dd3ef561 which I think made it into ubuntu around their 19.04 (?) release

https://launchpad.net/ubuntu/+source/packagekit

Furthermore this wouldn't work even without the breaking patch because of this change https://salsa.debian.org/pkgutopia-team/packagekit/commit/b486525502003ff9315ddb0dc6fb83c08219e7c4 that removed the python api and is part of ubuntu since 18.04 (possibly earlier).

So from a quick look I'd say it's broken in all Debian derivatives because of the first patch and then additionally defunct on Ubuntu derivatives because of the removal of the python API. Why API is being removed to begin with is escaping me though.

**Comment by apachelogger** [comment]
@ximion ^

**Comment by ximion** [comment]
This feature is completely broken and should be removed completely so someone rewrites it properly (It has also even when it worked never worked on Debian and was a fun bug fountain).
However, aptcc shouldn't even advertise to support GetDistroUpgrades, that's another issue.

**Comment by aleixpol** [comment]
Then it should return something empty. Blocking or crashing is not a solution.

The fact that this was done at packaging level, doesn't make it but much more frustrating.

**Comment by ximion** [comment]
Looks like this support was actually dropped upstream already, but not completely. This is done now.
The bigger issue is that there was no PK release for so long that there is a huge pile of bugfixes that haven't made it into the distribution yet, this change is one of them.
@hughsie can you please make a release? I can make one as well if that's okay with you (but I think I am not in the PK group on Freedesktop, so I can't upload all the changes - when this was acted upon by the fd.o admins 4 years after I requested access, back then I decided that this wasn't necessary anymore ^^. So now, it may be easier if you'd do the release...)

**Comment by hughsie** [comment]
I was hoping to get the meson stuff in a new release...

**Comment by ximion** [comment]
Yeah, that would be sweet! But that seems stalled for a while now... I *may* be able to help out if needed...
