### ISSUE TITLE
Why pkcon swears at installed packages?

### ISSUE THREAD

**Issue by r3d9u11** [hughsie/PackageKit#371]
Hello. I faced a bit trouble when I scripted my software installation process:
pkcon returs error with message "package not found" when this package was already installed.

For example I have installed package wine-staging.
If I try to run "sudo pkcon install wine-staging" I'll got error:
```
$ sudo pkcon install wine-staging
Resolving                     [=========================]         Package not found: wine-staging
Command failed: This tool could not find any available package: No packages were found
```
and process returns error code (so, my script emergency stop, too).

Can pkcon check installed packages and just ignore it, like apt do that?

Thanks!

**Comment by hughsie** [comment]
This is by design I'm afraid.
