### ISSUE TITLE
packagekitd constantly accessing disk

### ISSUE THREAD

**Issue by am312** [hughsie/PackageKit#391]
I'm not seeing high CPU or memory but perhaps this issue is a dupe of [this one](https://github.com/hughsie/PackageKit/issues/286)?
fatrace says packagekitd keeps hitting these files:

`# ./fatrace -t --command=packagekitd --output=packagekitd.log --seconds=5`

[packagekitd.log](https://github.com/hughsie/PackageKit/files/4415698/packagekitd.log)

It does this once per second:

10:19:41        PackageKit          transaction /44326_dcdccddc completed, removing
10:19:41        PackageKit          emitting destroy /44326_dcdccddc
10:19:41        PackageKit          CreateTransaction method called
10:19:41        PackageKit          job count now 44331
10:19:41        PackageKit          trying to open database '/var/lib/PackageKit/transactions.db'
10:19:41        PackageKit          job count is now at 44330
10:19:41        PackageKit          transaction now new
10:19:41        PackageKit          setting sender to :1.45185
10:19:41        PackageKit          adding transaction 0x56396c506be0
10:19:41        PackageKit          sending object path: '/44331_daedeebe'
10:19:41        PackageKit          SetHints method called: locale=C, background=false, interactive=true, cache-age=4294967295
10:19:41        PackageKit          cache-age changed to 4294967295
10:19:41        PackageKit          GetUpdates method called
10:19:41        PackageKit          transaction now ready
10:19:41        PackageKit          changing transaction to exclusive mode
10:19:41        PackageKit          5 transactions in list, 1 committed but not finished
10:19:41        PackageKit          transaction now running
10:19:41        PackageKit          install uid now 1000
10:19:41        PackageKit          install cmdline now PackageKit: get-updates
10:19:41        PackageKit          setting role for /44331_daedeebe to get-updates
10:19:41        PackageKit-DNF      using cached sack DnfSack::release_ver[8]::filelists|remote
10:19:41        PackageKit          backend was running for 40 ms
10:19:41        PackageKit          emitting finished 'success', 40
10:19:41        PackageKit          transaction now finished
10:19:41        PackageKit          5 transactions in list, 0 committed but not finished

**Comment by hughsie** [comment]
> it appears Gnome keeps reactivating it

PackageKit doesn't 'do' anything on it's own, it only does a transaction when an application asks it to. I think the bug lies in whatever is asking PK to do.

**Comment by am312** [comment]
How can you tell what it is being asked to do and by which application it is being asked to do it?
