### ISSUE TITLE
pk-command-not-found should not hard-code "bash"

### ISSUE THREAD

**Issue by glennj** [hughsie/PackageKit#42]
Should be agnostic with respect to user's shell. Please remove string "bash: "

https://github.com/hughsie/PackageKit/blob/master/contrib/command-not-found/pk-command-not-found.c#L787

**Comment by wjt** [comment]
This is fixed by #60

**Comment by DimStar77** [comment]
> This is fixed by #60

Has been long merged, so let's close this issue
