### ISSUE TITLE
"Authentication is required to remove software" translation not applied

### ISSUE THREAD

**Issue by AsciiWolf** [hughsie/PackageKit#428]
It seems that translation of the "Authentication is required to remove software" string is not applied:
![packagekit_remove](https://user-images.githubusercontent.com/2339930/92150300-828e9280-ee1f-11ea-9ff1-b37e908bcfd0.png)

Fedora 33, PackageKit-1.2.0-4.fc33.x86_64

This string seems to be [translated](https://github.com/hughsie/PackageKit/blob/master/po/cs.po#L191) in my (Czech) language and its translation seem to be included in the 1.2.0 release.

**Comment by hughsie** [comment]
Hmm; PackageKit isn't responsible for showing this dialog. If you change your session to French or German is is untranslated there? If so, can you file a gnome-shell issue please.

**Comment by AsciiWolf** [comment]
Yeah, also untranslated:

![dialog_german](https://user-images.githubusercontent.com/2339930/92269108-cfd43800-eee3-11ea-9ea1-4d83164e191f.png)

However, I have tried other Polkit dialogs (for example the ones from systemctl) and they all were correctly translated. Only this PackageKit-related dialog from GNOME Software seems to have this issue.

**Comment by hughsie** [comment]
You're right! The /usr/share/polkit-1/actions/org.freedesktop.packagekit.policy seems to have lost it's translations!

**Comment by hughsie** [comment]
Built in F33 now too, thanks.
