### ISSUE TITLE
Could not resolve proxy: HTTP_PROXY 

### ISSUE THREAD

**Issue by yecril71pl** [hughsie/PackageKit#440]
h2. Step
```sh
    { pkcon get-updates; }
```

h2. Result
> Download (curl) error for 'http://download.opensuse.org/history/20201011/tumbleweed/repo/oss/repodata/repomd.xml': 
> Error code: Connection failed 
> Error message: Could not resolve proxy: HTTP_PROXY 

h2. Workaround
```sh
    { rm /var/lib/PackageKit/transactions.db; }
```

**Comment by hughsie** [comment]
I don't think that's a bugreport, sorry.
