### ISSUE TITLE
Packagekit daemon : exit immediately

### ISSUE THREAD

**Issue by pandom79** [hughsie/PackageKit#454]
Due to my library implementation, i need to force go out packagekitd just finished the job.
I tried to set "--immediate-exit" to packagekitd command line but it causes the crash of daemon.
How can i do that?

**Comment by hughsie** [comment]
> i need to force go out packagekitd just finished the job

That's not going to work very well. I think you need to fix the library.

**Comment by pandom79** [comment]
Unfortunately, I cannot change the library. It has a lock/unlock mechanism (mutex) linked packagekitd thread. Each operation requires shutdown and restart of the daemon otherwise i always get an error that it is locked. Setting the minimum timeout (ShutdownTimeout=1), it works well but seems require more seconds to shutdown (about 7-8 sec). 
How can i shutdown packagekitd daemon as soon as possible?

**Comment by ximion** [comment]
> It has a lock/unlock mechanism (mutex) linked packagekitd thread. Each operation requires shutdown and restart of the daemon otherwise i always get an error that it is locked.

That sounds like either a bug in the library locking code, or it's a library usage error - maybe you need to manually unlock it's cache once you performed the operations you wanted to do?
You can not explicitly restart the daemon whenever you want, that will break the DBus communication with client tools and will be incredibly racy. The daemon timeout exists to shut down the daemon only after all operations have been completed to not have it linger in the background forever (but keep it for a little while in case a client tool sends more tasks immediately, which very often happens).

**Comment by pandom79** [comment]
Ok. Thanks.
