### ISSUE TITLE
alpm: Implement "update event"

### ISSUE THREAD

**Issue by lestofante** [hughsie/PackageKit#458]
If i run manual updates, Discovery (that uses PackageKit) has no way to know and does not see the updates as "done" until next automatic check for updates

As reference: https://bugs.kde.org/show_bug.cgi?id=426337

**Comment by ximion** [comment]
PackageKit on its own can't know unless your Linux distribution implements support to let it know about that fact. So this isn't really a PackageKit issue, but much rather an issue with your distribution/distro-backend.
E.g. on Debian, the package manager is configured to ping PackageKit in case updates have changed: https://github.com/hughsie/PackageKit/blob/master/backends/aptcc/20packagekit
Your OS needs to do something similar.

**Comment by aleixpol** [comment]
> E.g. on Debian, the package manager is configured to ping PackageKit in case updates have changed: https://github.com/hughsie/PackageKit/blob/master/backends/aptcc/20packagekit

aptcc and alpm backends are part of PackageKit not part of Debian or ArchLinux respectively. Hence it's an issue in PackageKit's alpm backend.

I see @zzag here did it already, it's a matter of integrating it in the buildsystem. https://gist.github.com/zzag/94d3c9c522332e0186d01b4636a391fe

**Comment by zzag** [comment]
There's an Arch Linux feature request to add such a post-transaction hook https://bugs.archlinux.org/task/69041. Should it be closed?

**Comment by lestofante** [comment]
@aleixpol said this should be implemented into PakageKit, so the feature request in arch should be closed, not this one.
AFAIK we need your script in the folder and then add to the meson build

```
install_data(
  '90-refresh-packagekit.hook',
  install_dir: join_paths(get_option('sysconfdir'), 'pacman.d', 'hooks'),
)
```

**Comment by zzag** [comment]
Okay, I created a merge request. #459
