### ISSUE TITLE
Possible memory leak with dnf backend

### ISSUE THREAD

**Issue by kkartaltepe** [hughsie/PackageKit#460]
packagekitd consumes what I think is an unreasonable amount of memory, especially for a daemon intended to be running at all times. On my system it quickly consumes several hundred MB and after some time typically grows beyond 800MB resident memory.

When profiled on fedora you you can see it allocates upwards of 60MB of heap space per what ill call "a bad query". When viewing the systemd unit you can see that the heap profiler reports ~150GB of allocations to satisfy the query before reporting
`get-update-detail transaction /2154_ceebebbb from uid 1000 finished with success after 265536ms`.

Attached is the pdf of the pprof output (i can provide the actual heap dumps as well from the full run if desired).
[dump.pdf](https://github.com/hughsie/PackageKit/files/6134308/dump.pdf)

Tested on fedora 33.
PackageKit 1.2.2
Probable caller of the "bad query" gnome-software.

**Comment by hughsie** [comment]
Isn't this a libdnf issue?

**Comment by kkartaltepe** [comment]
I have no clue about the architecture of packagekit, so it may be.

**Comment by ximion** [comment]
> especially for a daemon intended to be running at all times

That's odd, the daemon should terminate itself after a timeout when it's not in use...

**Comment by kkartaltepe** [comment]
on fedora it never terminates for me. The last log from the systemd unit was 6 hours ago but it happily sitting there consuming memory.

**Comment by kkartaltepe** [comment]
well i think that may be one issue, considering it seems dnf sacks never free repo data so it may expect you to exit.

However ive gotten packagekit bloated to 900MB of resident but am a bit baffled. Heap profiler can only find 300MB of live heap, and when the process starts its like 150MB of executable, which leaves 350MB of something which im not sure what it could be other than very huge stack frames?

**Comment by kkartaltepe** [comment]
I havnt had luck with any tooling to dig in further and dont want to spend more time trying to replicate this over days and weeks, so ill close out this bug. Thanks for taking a look sorry I couldn't pin it down to anything actionable.

**Comment by YaBoiBurner** [comment]
i know it's a little late but if you wanna make sure packagekit terminates after a while, uncomment the line `#ShutdownTimeout=300` in `/etc/PackageKit/PackageKit.conf`
