### ISSUE TITLE
Failed to start Import ZFS pools by cache file

### ISSUE THREAD

**Issue by felimwhiteley** [hughsie/PackageKit#466]
Hi Folks,

My current system running KDE Neon has / as a luks encrypted ext4 with a separate ZFS pool (called: pdr) where I store various datasets. I've switched to the offline updates in the past month but on several occasion on boot the ZFS pool is offline. I can fix the issue with a zfs import so it's no big deal, but for users unaware of that (and I'm not sure what would happen with / on zfs) their data appears to have dissappeared.

I has happened this morning and on the 31st of March, I'll include what packages were in those updates. I'm not sure if it is related to the packages that were updated or if it is coincidence. I've never had this happen with a normal 
```
sudo apt update && sudo apt full-upgrade && sudo apt autoremove
```

The pkcon upgrade I'm doing is:
```
pkcon refresh && pkcon update --only-download && pkcon offline-trigger
```
The error I see in boot journal is:
```
Mar 31 22:13:20 monolith systemd[1]: Starting Import ZFS pools by cache file...
Mar 31 22:13:20 monolith systemd[1]: Failed to start Import ZFS pools by cache file.
```
```
Apr 13 07:51:54 monolith systemd[1]: Starting Import ZFS pools by cache file...
Apr 13 07:51:54 monolith systemd[1]: Failed to start Import ZFS pools by cache file.
```
[packages-2021-03-31-2211hrs.log](https://github.com/hughsie/PackageKit/files/6302193/packages-2021-03-31-2211hrs.log)
[packages-2021-04-13-0734hrs.log](https://github.com/hughsie/PackageKit/files/6302194/packages-2021-04-13-0734hrs.log)

If I search back through the boot events with the following
```
journalctl -b -1 | grep "Import ZFS pools"
```
The boot preceeding the faliure to mount the ZFS finds no import ZFS message, so the -1 boot in this case and the -9 boot prior to the -10 boot on the 31s March which failed. I'm not sure what other logs would help here but happy to provide them.

[boot-2021-04-13-0734-install.log](https://github.com/hughsie/PackageKit/files/6302486/boot-2021-04-13-0734-install.log)
[boot-2021-04-13-0734-zfs-fail.log](https://github.com/hughsie/PackageKit/files/6302509/boot-2021-04-13-0734-zfs-fail.log)

Hope that contains enough info in the two boot logs...

**Comment by hughsie** [comment]
I don't think this is a PackageKit problem I'm afraid.

**Comment by felimwhiteley** [comment]
It's only started happening since using pkcon... Maybe I should try test it in a VM to see can I recreate it, so I could compare whether the apt versus the pkcon is really the differentiator. But I've never had this happen before.

**Comment by felimwhiteley** [comment]
Never happen over 3 years of having ZFS on this machine I should clarify, then in the last 5-6weeks tried the offline updates and it's cropped up about 3 or 4 times.

**Comment by apachelogger** [comment]
I rather suspect zfs-linux is to blame as this sounds a whole lot like a unit race of sorts.

I haven't looked at all the units but [1] mainly anchors on [2] and that only anchors on multi-user.target which I'm not even sure is reached for offline, so for all I know import-cache isn't even part of the unit chain leading to packagekit-offline-update. respectively system-update.target. In any event, since zfs doesn't log why it failed I'm not sure what we can do about it from the packagekit side. 

[1] https://sources.debian.org/src/zfs-linux/2.0.3-6/etc/systemd/system/zfs-import-cache.service.in/
[2] https://sources.debian.org/src/zfs-linux/2.0.3-6/etc/systemd/system/zfs.target.in/

**Comment by felimwhiteley** [comment]
Hmm yeah that sounds plausible alright, I'll fire it over to them. Thanks for the prompt updates @hughsie @apachelogger I'll close this as I reckon you're both right.
