### ISSUE TITLE
gtk3 Library Needs New i386 Version

### ISSUE THREAD

**Issue by mail11325** [hughsie/PackageKit#467]
I'm running a IBM Thinkpad i386. Firefox and Thunderbird has been frozen since October 2020. I finally fixed the problem.

On the Centos Software Installer, under the Thunderbird Requires button, Thunderbird requires gtk3-3.22.30-6.el7 32 bit.

When I installed gtk3-devel-3.22.30-6.el7  Thunderbird launched without freezing again. Firefox was also successful launched.

Request you ungrade the Thunderbird and Firefox Software Installer to automatically push gtk3-3.22.30-6.el7   for 32 bit installations. Thanks.

If you can't help me, please direct me to a Centos point of contact for this issue.

Tom Herman
mail11325@bellsouth.net
mail11325@gmail.com

**Comment by hughsie** [comment]
Not a packagekit issue.
