### ISSUE TITLE
Katja backend segmentation fault.

### ISSUE THREAD

**Issue by saxa** [hughsie/PackageKit#48]
Hi, in the PackageKit 1.0.3 and 1.0.5 versions I get a segmentation fault when doing a pkcon install dropline . 

It seems that the offending piece of code is g_strreverse() used in katja-utils.c at line 79.

See the debug and verbose output of the packagekitd:

rc@rclaptop:~$ su -
Password: 
root@rclaptop:~# pkcon refresh force
Refreshing cache              [=========================]  
Waiting for authentication    [=========================]  
Downloading lists of changes  [=========================]  
Downloading repository information[=========================]  
Refreshing software list      [=========================]  
Finished                      [=========================]  
root@rclaptop:~# pkcon install dropline
Resolving                     [                         ](0%)  

Here is the log on another terminal.

root@rclaptop:~# killall packagekitd
packagekitd: no process found
root@rclaptop:~# /usr/libexec/packagekitd --verbose --backend=katja
16:30:57    PackageKit          Verbose debugging enabled (on console 1)
16:30:57    PackageKit          daemon shutdown set to 0 seconds
16:30:57    PackageKit          clearing download cache at /var/cache/PackageKit/downloads
16:30:57    PackageKit          destination eth0 is valid
16:30:57    PackageKit          setting config file watch on /etc/PackageKit/PackageKit.conf
16:30:57    PackageKit          Trying to load : katja
16:30:57    PackageKit          dlopening '/usr/lib64/packagekit-backend/libpk_backend_katja.so'
16:30:57    PackageKit          trying to open database '/var/lib/PackageKit/transactions.db'
16:30:57    PackageKit          job count is now at 0
16:30:57    PackageKit          is_default: 1
16:30:57    PackageKit          network state is wired
16:30:57    PackageKit          emitting network-state-changed: wired
16:30:57    PackageKit          PkEngine: acquired name: org.freedesktop.PackageKit
16:31:25    PackageKit          CreateTransaction method called
16:31:25    PackageKit          job count now 1
16:31:25    PackageKit          trying to open database '/var/lib/PackageKit/transactions.db'
16:31:25    PackageKit          job count is now at 0
16:31:25    PackageKit          transaction now new
16:31:25    PackageKit          setting sender to :1.108
16:31:25    PackageKit          adding transaction 0x7f224d1eb240
16:31:25    PackageKit          sending object path: '/1_cadbeddd'
16:31:25    PackageKit          notify::connected
16:31:25    PackageKit          SetHints method called: locale=en_US.UTF-8, background=false, interactive=true, cache-age=4294967295
16:31:25    PackageKit          RefreshCache method called: 1
16:31:25    PackageKit          transaction now waiting-for-auth
16:31:25    PackageKit          authorizing action org.freedesktop.packagekit.system-sources-refresh
16:31:25    PackageKit          transaction now ready
16:31:25    PackageKit          changing transaction to exclusive mode
16:31:25    PackageKit          1 transactions in list, 1 committed but not finished
16:31:25    PackageKit          transaction now running
16:31:25    PackageKit          locale changed to en_US.UTF-8
16:31:25    PackageKit          cache-age changed to -1
16:31:25    PackageKit          Failed to get session for :1.108: GDBus.Error:org.freedesktop.ConsoleKit.Manager.GeneralError: Unable to lookup session information for process '3631'
16:31:25    PackageKit          failed to set the session state (non-fatal): failed to get the session
16:31:25    PackageKit          setting role for /1_cadbeddd to refresh-cache
16:31:27    PackageKit          State:
0   refresh-cache   /1_cadbeddd state[running] exclusive[1] background[0]

16:31:27    PackageKit          1 are running
HTTP/1.1 200 OK
Date: Thu, 05 Mar 2015 15:32:58 GMT
Server: Apache
Last-Modified: Tue, 03 Mar 2015 20:41:40 GMT
ETag: "ba18-510685c9d2900"
Accept-Ranges: bytes
Content-Length: 47640
Content-Type: text/plain

HTTP/1.1 302 Found
Date: Thu, 05 Mar 2015 15:32:59 GMT
Server: Apache/2.4.10 (Unix)
X-MirrorBrain-Mirror: muzzy
X-MirrorBrain-Realm: country
Link: http://mirrors.slackware.com/slackware/slackware64-14.1/patches/PACKAGES.TXT.meta4; rel=describedby; type="application/metalink4+xml"
Link: http://slackware.muzzy.it/slackware64-14.1/patches/PACKAGES.TXT; rel=duplicate; pri=1; geo=it
Link: http://www.slackware.at/data/slackware64-14.1/patches/PACKAGES.TXT; rel=duplicate; pri=2; geo=at
Link: http://mirror.slackware.hr/slackware/slackware64-14.1/patches/PACKAGES.TXT; rel=duplicate; pri=3; geo=hr
Link: http://mirror.netcologne.de/slackware/slackware64-14.1/patches/PACKAGES.TXT; rel=duplicate; pri=4; geo=de
Link: http://ftp5.gwdg.de/pub/linux/slackware/slackware64-14.1/patches/PACKAGES.TXT; rel=duplicate; pri=5; geo=de
Digest: MD5=DZKkxnVSnZgXWYPyg91ENw==
Digest: SHA=ldtAfGcjns695+LITr0S4vwrHQY=
Digest: SHA-256=wLJam31iasdG8zs1O0h+v1gThjLHMQuroTgo+TbijQs=
Location: http://slackware.muzzy.it/slackware64-14.1/patches/PACKAGES.TXT
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Thu, 05 Mar 2015 15:32:59 GMT
Server: Apache
Last-Modified: Thu, 26 Feb 2015 01:16:40 GMT
ETag: "27200d4-9e9e-50ff3810aee00"
Accept-Ranges: bytes
Content-Length: 40606
Vary: Accept-Encoding
Content-Type: text/plain

HTTP/1.1 302 Found
Date: Thu, 05 Mar 2015 15:33:00 GMT
Server: Apache/2.4.10 (Unix)
X-MirrorBrain-Mirror: muzzy
X-MirrorBrain-Realm: country
Link: http://mirrors.slackware.com/slackware/slackware64-14.1/patches/MANIFEST.bz2.meta4; rel=describedby; type="application/metalink4+xml"
Link: http://slackware.muzzy.it/slackware64-14.1/patches/MANIFEST.bz2; rel=duplicate; pri=1; geo=it
Link: http://www.slackware.at/data/slackware64-14.1/patches/MANIFEST.bz2; rel=duplicate; pri=2; geo=at
Link: http://mirror.slackware.hr/slackware/slackware64-14.1/patches/MANIFEST.bz2; rel=duplicate; pri=3; geo=hr
Link: http://mirror.netcologne.de/slackware/slackware64-14.1/patches/MANIFEST.bz2; rel=duplicate; pri=4; geo=de
Link: http://ftp5.gwdg.de/pub/linux/slackware/slackware64-14.1/patches/MANIFEST.bz2; rel=duplicate; pri=5; geo=de
Digest: MD5=mOV/KZDW5rXsgAP3VYPg+g==
Digest: SHA=vaMvAYiEz8sXcg9yeUiKjCDj29U=
Digest: SHA-256=DdXhf9I+C2niMDjU45r5QVm8iBf7BIAIw+pEvN5HUbE=
Location: http://slackware.muzzy.it/slackware64-14.1/patches/MANIFEST.bz2
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Thu, 05 Mar 2015 15:33:00 GMT
Server: Apache
Last-Modified: Thu, 26 Feb 2015 01:16:34 GMT
ETag: "27200ed-3fd2f4-50ff380af6080"
Accept-Ranges: bytes
Content-Length: 4182772
Content-Type: application/x-bzip2

HTTP/1.1 302 Found
Date: Thu, 05 Mar 2015 15:33:00 GMT
Server: Apache/2.4.10 (Unix)
X-MirrorBrain-Mirror: muzzy
X-MirrorBrain-Realm: country
Link: http://mirrors.slackware.com/slackware/slackware64-14.1/slackware64/PACKAGES.TXT.meta4; rel=describedby; type="application/metalink4+xml"
Link: http://slackware.muzzy.it/slackware64-14.1/PACKAGES.TXT; rel=duplicate; pri=1; geo=it
Link: http://www.slackware.at/data/slackware64-14.1/PACKAGES.TXT; rel=duplicate; pri=2; geo=at
Link: http://mirror.slackware.hr/slackware/slackware64-14.1/PACKAGES.TXT; rel=duplicate; pri=3; geo=hr
Link: http://mirror.netcologne.de/slackware/slackware64-14.1/PACKAGES.TXT; rel=duplicate; pri=4; geo=de
Link: http://ftp5.gwdg.de/pub/linux/slackware/slackware64-14.1/PACKAGES.TXT; rel=duplicate; pri=5; geo=de
Digest: MD5=uRbTnYrVDOv7D9bP4yBhXw==
Digest: SHA=u+oad+o9bFRnmLWX/kUo+xei2ng=
Digest: SHA-256=R18j25g3PxC2bf5JeAaI3D3o5E9nzDdX66LMW6CmpfM=
Location: http://slackware.muzzy.it/slackware64-14.1/PACKAGES.TXT
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Thu, 05 Mar 2015 15:33:00 GMT
Server: Apache
Last-Modified: Sun, 03 Nov 2013 06:19:37 GMT
ETag: "181c58-a2411-4ea3fc8a5f040"
Accept-Ranges: bytes
Content-Length: 664593
Vary: Accept-Encoding
Content-Type: text/plain

HTTP/1.1 302 Found
Date: Thu, 05 Mar 2015 15:33:00 GMT
Server: Apache/2.4.10 (Unix)
X-MirrorBrain-Mirror: muzzy
X-MirrorBrain-Realm: country
Link: http://mirrors.slackware.com/slackware/slackware64-14.1/slackware64/MANIFEST.bz2.meta4; rel=describedby; type="application/metalink4+xml"
Link: http://slackware.muzzy.it/slackware64-14.1/slackware64/MANIFEST.bz2; rel=duplicate; pri=1; geo=it
Link: http://www.slackware.at/data/slackware64-14.1/slackware64/MANIFEST.bz2; rel=duplicate; pri=2; geo=at
Link: http://mirror.slackware.hr/slackware/slackware64-14.1/slackware64/MANIFEST.bz2; rel=duplicate; pri=3; geo=hr
Link: http://mirror.netcologne.de/slackware/slackware64-14.1/slackware64/MANIFEST.bz2; rel=duplicate; pri=4; geo=de
Link: http://ftp5.gwdg.de/pub/linux/slackware/slackware64-14.1/slackware64/MANIFEST.bz2; rel=duplicate; pri=5; geo=de
Digest: MD5=STC75EM6k4xau50rRUvi4Q==
Digest: SHA=ZOOkKq58vC6h9wqft/jyVS6mKxY=
Digest: SHA-256=Vqs2OjQweenSPvQKIW4pfZBJkEhXBfsJjdcZV+eQil8=
Location: http://slackware.muzzy.it/slackware64-14.1/slackware64/MANIFEST.bz2
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Thu, 05 Mar 2015 15:33:00 GMT
Server: Apache
Last-Modified: Sun, 03 Nov 2013 06:19:05 GMT
ETag: "2720173-2b94bc-4ea3fc6bda840"
Accept-Ranges: bytes
Content-Length: 2856124
Content-Type: application/x-bzip2

HTTP/1.1 302 Found
Date: Thu, 05 Mar 2015 15:33:00 GMT
Server: Apache/2.4.10 (Unix)
X-MirrorBrain-Mirror: muzzy
X-MirrorBrain-Realm: country
Link: http://mirrors.slackware.com/slackware/slackware64-14.1/extra/PACKAGES.TXT.meta4; rel=describedby; type="application/metalink4+xml"
Link: http://slackware.muzzy.it/slackware64-14.1/extra/PACKAGES.TXT; rel=duplicate; pri=1; geo=it
Link: http://www.slackware.at/data/slackware64-14.1/extra/PACKAGES.TXT; rel=duplicate; pri=2; geo=at
Link: http://mirror.slackware.hr/slackware/slackware64-14.1/extra/PACKAGES.TXT; rel=duplicate; pri=3; geo=hr
Link: http://mirror.netcologne.de/slackware/slackware64-14.1/extra/PACKAGES.TXT; rel=duplicate; pri=4; geo=de
Link: http://ftp5.gwdg.de/pub/linux/slackware/slackware64-14.1/extra/PACKAGES.TXT; rel=duplicate; pri=5; geo=de
Digest: MD5=LuCSbQdKT/Y3I7Wf9mRvjA==
Digest: SHA=2TM9HybiHYmD0Yy43UVRe1My34s=
Digest: SHA-256=P86R2Lqlct0Z25RAcBqPtk3TQu+1bdv6FMNtO3INyCc=
Location: http://slackware.muzzy.it/slackware64-14.1/extra/PACKAGES.TXT
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Thu, 05 Mar 2015 15:33:00 GMT
Server: Apache
Last-Modified: Mon, 21 Oct 2013 07:36:20 GMT
ETag: "1c11f3-7bd7-4e93b57124500"
Accept-Ranges: bytes
Content-Length: 31703
Vary: Accept-Encoding
Content-Type: text/plain

HTTP/1.1 302 Found
Date: Thu, 05 Mar 2015 15:33:00 GMT
Server: Apache/2.4.10 (Unix)
X-MirrorBrain-Mirror: muzzy
X-MirrorBrain-Realm: country
Link: http://mirrors.slackware.com/slackware/slackware64-14.1/extra/MANIFEST.bz2.meta4; rel=describedby; type="application/metalink4+xml"
Link: http://slackware.muzzy.it/slackware64-14.1/extra/MANIFEST.bz2; rel=duplicate; pri=1; geo=it
Link: http://www.slackware.at/data/slackware64-14.1/extra/MANIFEST.bz2; rel=duplicate; pri=2; geo=at
Link: http://mirror.slackware.hr/slackware/slackware64-14.1/extra/MANIFEST.bz2; rel=duplicate; pri=3; geo=hr
Link: http://mirror.netcologne.de/slackware/slackware64-14.1/extra/MANIFEST.bz2; rel=duplicate; pri=4; geo=de
Link: http://ftp5.gwdg.de/pub/linux/slackware/slackware64-14.1/extra/MANIFEST.bz2; rel=duplicate; pri=5; geo=de
Digest: MD5=eLkzww8D6JHQeemB8RgdDw==
Digest: SHA=68c7V1P9+6PSokaOPmwcGO24Aig=
Digest: SHA-256=5NplT1ne5C6ryDNnZgfubkCrFWm/AuAqO2rFH1JrxuE=
Location: http://slackware.muzzy.it/slackware64-14.1/extra/MANIFEST.bz2
Content-Type: text/html; charset=iso-8859-1

HTTP/1.1 200 OK
Date: Thu, 05 Mar 2015 15:33:01 GMT
Server: Apache
Last-Modified: Mon, 21 Oct 2013 07:36:18 GMT
ETag: "1c11f2-163e9-4e93b56f3c080"
Accept-Ranges: bytes
Content-Length: 91113
Content-Type: application/x-bzip2

HTTP/1.1 200 OK
Date: Thu, 05 Mar 2015 15:33:01 GMT
Server: Apache/2.4.10 (Unix)
Last-Modified: Thu, 16 May 2013 00:17:52 GMT
ETag: "49d-4dccacc10cc00"
Accept-Ranges: bytes
Content-Length: 1181
Content-Type: text/plain

HTTP/1.1 200 OK
Date: Thu, 05 Mar 2015 15:33:01 GMT
Server: Apache/2.4.10 (Unix)
Last-Modified: Thu, 16 May 2013 00:17:52 GMT
ETag: "86a-4dccacc10cc00"
Accept-Ranges: bytes
Content-Length: 2154
Content-Type: application/x-bzip2

HTTP/1.1 200 OK
Date: Thu, 05 Mar 2015 15:33:01 GMT
Server: Apache/2.4.10 (Unix)
Last-Modified: Mon, 04 Nov 2013 02:40:40 GMT
ETag: "34d-4ea50d7769a00"
Accept-Ranges: bytes
Content-Length: 845
Content-Type: text/plain

HTTP/1.1 200 OK
Date: Thu, 05 Mar 2015 15:33:01 GMT
Server: Apache/2.4.10 (Unix)
Last-Modified: Mon, 04 Nov 2013 02:40:40 GMT
ETag: "375-4ea50d7769a00"
Accept-Ranges: bytes
Content-Length: 885
Content-Type: application/x-bzip2

16:31:37    PackageKit          State:
0   refresh-cache   /1_cadbeddd state[running] exclusive[1] background[0]

16:31:37    PackageKit          1 are running
16:31:47    PackageKit          State:
0   refresh-cache   /1_cadbeddd state[running] exclusive[1] background[0]

16:31:47    PackageKit          1 are running
16:31:57    PackageKit          State:
0   refresh-cache   /1_cadbeddd state[running] exclusive[1] background[0]

16:31:57    PackageKit          1 are running
16:32:07    PackageKit          State:
0   refresh-cache   /1_cadbeddd state[running] exclusive[1] background[0]

16:32:07    PackageKit          1 are running

(packagekitd:3528): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
16:32:12    PackageKit          directory dropline found in /tmp/PackageKit.QBA6UX, deleting
16:32:12    PackageKit          file found in /tmp/PackageKit.QBA6UX/dropline, deleting
16:32:12    PackageKit          directory slackware found in /tmp/PackageKit.QBA6UX, deleting
16:32:12    PackageKit          file found in /tmp/PackageKit.QBA6UX/slackware, deleting
16:32:12    PackageKit          file found in /tmp/PackageKit.QBA6UX/slackware, deleting
16:32:12    PackageKit          file found in /tmp/PackageKit.QBA6UX/slackware, deleting
16:32:12    PackageKit          file found in /tmp/PackageKit.QBA6UX/slackware, deleting
16:32:12    PackageKit          file found in /tmp/PackageKit.QBA6UX/slackware, deleting
16:32:12    PackageKit          file found in /tmp/PackageKit.QBA6UX/slackware, deleting
16:32:12    PackageKit          backend was running for 47270 ms
16:32:12    PackageKit          emitting finished 'success', 47270
16:32:12    PackageKit          transaction now finished
16:32:12    PackageKit          1 transactions in list, 0 committed but not finished
16:32:12    PackageKit          emitting updates-changed
16:32:12    PackageKit          emitting updates-changed
16:32:17    PackageKit          transaction /1_cadbeddd completed, removing
16:32:17    PackageKit          emitting destroy /1_cadbeddd
16:32:31    PackageKit          CreateTransaction method called
16:32:31    PackageKit          job count now 2
16:32:31    PackageKit          trying to open database '/var/lib/PackageKit/transactions.db'
16:32:31    PackageKit          job count is now at 0
16:32:31    PackageKit          transaction now new
16:32:31    PackageKit          setting sender to :1.110
16:32:31    PackageKit          adding transaction 0x7f224d1eb3e0
16:32:31    PackageKit          sending object path: '/2_eedeedae'
16:32:31    PackageKit          notify::connected
16:32:31    PackageKit          SetHints method called: locale=en_US.UTF-8, background=false, interactive=true, cache-age=4294967295
16:32:31    PackageKit          Resolve method called: 2424840, dropline
16:32:31    PackageKit          transaction now ready
16:32:31    PackageKit          changing transaction to exclusive mode
16:32:31    PackageKit          1 transactions in list, 1 committed but not finished
16:32:31    PackageKit          transaction now running
16:32:31    PackageKit          locale changed to en_US.UTF-8
16:32:31    PackageKit          cache-age changed to -1
16:32:31    PackageKit          Failed to get session for :1.110: GDBus.Error:org.freedesktop.ConsoleKit.Manager.GeneralError: Unable to lookup session information for process '3643'
16:32:31    PackageKit          failed to set the session state (non-fatal): failed to get the session
16:32:31    PackageKit          setting role for /2_eedeedae to resolve
Segmentation fault
root@rclaptop:~#

Here is the output when run in gdb:

16:51:09    PackageKit          SetHints method called: locale=en_US.UTF-8, background=false, interactive=true, cache-age=4294967295
16:51:09    PackageKit          Resolve method called: 2424840, dropline
16:51:09    PackageKit          transaction now ready
16:51:09    PackageKit          changing transaction to exclusive mode
16:51:09    PackageKit          1 transactions in list, 1 committed but not finished
16:51:09    PackageKit          transaction now running
16:51:09    PackageKit          locale changed to en_US.UTF-8
16:51:09    PackageKit          cache-age changed to -1
16:51:09    PackageKit          Failed to get session for :1.118: GDBus.Error:org.freedesktop.ConsoleKit.Manager.GeneralError: Unable to lookup session information for process '3947'
16:51:09    PackageKit          failed to set the session state (non-fatal): failed to get the session
16:51:09    PackageKit          setting role for /2_deddeecd to resolve
[New Thread 0x7fffec834700 (LWP 3957)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffec834700 (LWP 3957)]
0x00007ffff600154e in g_strreverse () from /usr/lib64/../lib64/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff600154e in g_strreverse () from /usr/lib64/../lib64/libglib-2.0.so.0
#1  0x00007fffee5a44df in katja_cut_pkg () from /usr/lib64/packagekit-backend/libpk_backend_katja.so
#2  0x00007fffee5a4643 in katja_pkg_is_installed () from /usr/lib64/packagekit-backend/libpk_backend_katja.so
#3  0x00007fffee59fcf6 in ?? () from /usr/lib64/packagekit-backend/libpk_backend_katja.so
#4  0x00005555555735ba in ?? ()
#5  0x00007ffff0004000 in ?? ()
#6  0x00007ffff6008f95 in ?? () from /usr/lib64/../lib64/libglib-2.0.so.0
#7  0x00007ffff5d86ce2 in start_thread () from /lib64/libpthread.so.0
#8  0x00007ffff5aaf8cd in clone () from /lib64/libc.so.6

(gdb) n
Single stepping until exit from function g_strreverse,
which has no line number information.
[Thread 0x7fffec834700 (LWP 3957) exited]
[Thread 0x7fffed23b700 (LWP 3955) exited]
[Thread 0x7fffeefa8700 (LWP 3815) exited]
[Thread 0x7ffff5772700 (LWP 3813) exited]
[Thread 0x7ffff7fb4740 (LWP 3809) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb)

I will see if I can build it also with -g option enabled and include more debug symbols.

**Comment by belka-ew** [comment]
#65
