### ISSUE TITLE
Return information about installed package origin

### ISSUE THREAD

**Issue by fbourigault** [hughsie/PackageKit#55]
In GNOME Software "Software sources", we can see the Arch Linux repositories. As you can notice in the screenshot, there is no information about apps installed from each repos.

This is not easy to fix because libalpm don't record the package origin when installed. A lookup through syncdb is possible, but if a package is available from multiple repos, I will not be able to display the right repos.

An other problem is that the core repository does not provide applications, so an user can disable this repos and thus upgrades will be inconsistent and system may be unusable.

![Software Sources](https://cloud.githubusercontent.com/assets/1116116/6725961/12b8c14e-ce11-11e4-98c2-f08750d32d2f.png)

IMHO a possible solution would be to record the info in libalpm. I don't know yet if it's possible but I will ask.

In case it's possible, what it the use case for manually installed applications (i.e. `pacman -U some-application-1.0-x86_64.pkg.tar.xz`) ?

What happen if a repos was disabled outside of gnome-software ?

An other ~stupid~ question, does disabling a software source should disable it system wide ?

cc @hughsie for the last 3 questions :)

**Comment by hughsie** [comment]
> In case it's possible, what it the use case for manually installed applications

I'd hope they are tracked too

> What happen if a repos was disabled outside of gnome-software ?

We should detect that, e.g. with a file notification.

> An other ~stupid~ question, does disabling a software source should disable it system wide ?

Yup.

**Comment by fbourigault** [comment]
>> In case it's possible, what it the use case for manually installed applications

>I'd hope they are tracked too

It's just done using `installed` instead of `<repos>:installed` ?



>>    What happen if a repos was disabled outside of gnome-software ?

>We should detect that, e.g. with a file notification.

Ok, I will need to watch `/etc/pacman.conf` and do the same thing that I did for local database external changes.



>> An other ~stupid~ question, does disabling a software source should disable it system wide ?

> Yup.

This will be tricky. As of today, when a repo is disabled, it's only in the packagekit internals. I will have to edit the /etc/pacman.conf file.

**Comment by fbourigault** [comment]
I also have a new question. If user enable a testing repos, he will have two repos providing gnome-maps for exemple. Because user have his system up to date, the testing version is installed. If he want to disable the testing repos, gnome-maps will be removed but, IMHO, the user wanted to downgrade to gnome-maps from the stable repos. What is the right behavior in this use case ?

**Comment by hughsie** [comment]
I'm not sure there is a good answer for this. I guess we could handle downgrading as part of repo removal, but it might be best just not to show the testing repo in this list.

**Comment by fbourigault** [comment]
Not showing testing repos is fine to me as it's for advanced users.

**Comment by fbourigault** [comment]
>>>In case it's possible, what it the use case for manually installed applications

>>I'd hope they are tracked too

> It's just done using installed instead of <repos>:installed ?

It seems that fedora use local for <repos> for manually installed packages.

**Comment by Catanzaro** [comment]
See also https://bugzilla.gnome.org/show_bug.cgi?id=732406

**Comment by fbourigault** [comment]
The current plan is to remove the enable/disable feature from backend because it's only toggle repository in packagekit internals and don't do it in pacman.conf

**Comment by aleixpol** [comment]
Regarding downgrade, disabling a repository doesn't necessarily mean you want to downgrade all the packages from the source. They can belong then in an "unknown source" kind of category, together with the "pacman -U" use-case.

And yes, I agree that we should disable the repositories system-wide rather than exclusively in packagekit.

I hope this helps...

**Comment by fbourigault** [comment]
I'm closing this issue as I'm no longer hacking on PackageKit.

**Comment by ximion** [comment]
@fbourigault You know, you not working on this issue doesn't make it disappear - maybe someone else wants to work on it?
In any case, as long as it isn't resolved, it should be left open.

**Comment by fbourigault** [comment]
I know but it add noise on my GitHub issue view.

**Comment by ximion** [comment]
You know that you can just hit the "Unsubscribe" button to the right?
And also, this is a very very bad reason to make it harder for everyone else to find information on issues they want to work on.

**Comment by fbourigault** [comment]
Unsubscribe does not remove the issue from the list (https://github.com/issues)
