### ISSUE TITLE
Paralellization of "read" operations

### ISSUE THREAD

**Issue by fbourigault** [hughsie/PackageKit#59]
I know that alpm backend does not support paralellization but when testing some code before pushing, I ran in something strange. I launched a `pkcon update` and then launched gnome-software. As you can see in the screenshot, the backend is busy on the update task so it can't perform the read tasks required by Software. I think same behavior happens with every backend that does not support paralellization.

I also notice that it also happens when installing an app and while it's not finished going to other application pages. I only get an empty page with loader image.

What could be improved here to easly support parallel read operations ? Maybe we could have a intermediate level of paralellization that allow clients to do some operations in parallel ?

![capture d ecran de 2015-03-19 23 00 01](https://cloud.githubusercontent.com/assets/1116116/6741989/6e3b559c-ce8c-11e4-8ad8-d89914cb64c0.png)

cc @hughsie

**Comment by ximion** [comment]
When first thinking about parallelization, my plan was to implement it client-side, so the server would do write operation and the client would perform read operations directly.
This wasn't liked very much by hughsie, and after some discussion lead to the current design, which is much cleaner and nicer to understand and work with.
Unfortunately, most of the PMs aren't threadsafe.
So what you could do, and what we were thinking about doing for the aptcc backend, is forking a new process out of packagekitd when running an operation. It sounds (and is) ugly, but could be a viable solution.
The other options would be creating a threadsafe wrapper around your PM, or convincing hughsie to accept a solution which would not require a threadsafe backend. The latter could maybe be done by implementing a generic framework for multiprocess C/C++ backends in PackageKit, which would not have the issues a spwned backend has, but still allow non-threadsafe backends to support parallel transactions.

**Comment by fbourigault** [comment]
I'm closing this issue as I'm no longer hacking on PackageKit.
