### ISSUE TITLE
Check local files against running machine architecture?

### ISSUE THREAD

**Issue by FedeDP** [hughsie/PackageKit#87]
Hi!

Is there a way for packagekit to check for running machine arch matching against files waiting to be installed arch?
Now pkcon just crashes:
"
LC_ALL=C pkcon install-local pulseaudio-7.0-2-i686.pkg.tar.xz
Installing files              [=========================]         
Testing changes               [  ==                     ]         The daemon crashed mid-transaction!
"
(on archlinux x86_64)

**Comment by kkofler** [comment]
This is really something for the backend to handle. Some distributions allow installing i686 packages on x86_64 just fine, it depends on whether and how multilib is set up on the distribution.

**Comment by FedeDP** [comment]
You're probably right.  
If i understood that correctly, it seems apt backend checks for running architecture: https://github.com/hughsie/PackageKit/blob/master/backends/aptcc/deb-file.cpp#L93.
I only believe daemon should not crash, instead it should return an error code; am i wrong?

**Comment by hughsie** [comment]
The daemon should never crash. Can you get a backtrace of the crash please? Also a debug log (--verbose) would be helpful as well. Thanks!

**Comment by FedeDP** [comment]
gdb: http://pastie.org/10510984
--verbose: http://pastie.org/10510987
Hope these logs are fine :)

**Comment by hughsie** [comment]
Ahh, sorry, I wasn't clear. I need the gdb and logs of the packagekitd process, rather than pkcon. You can do this using something like:

    gdb packagekitd --verbose --backend=alpm

**Comment by FedeDP** [comment]
Hope this is fine: http://codepad.org/b7qUxX71.

**Comment by hughsie** [comment]
yup, looks good. Now do "bt" and attach the backtrace. Thanks.

**Comment by FedeDP** [comment]
http://codepad.org/A4FJWmDX, thanks for your guidance!

**Comment by FedeDP** [comment]
Still having the issue with packagekit 1.0.11:
"LC_ALL=C pkcon install-local pulseaudio-7.1-1-i686.pkg.tar.xz
Installing files              [                         ] (0%)  The daemon crashed mid-transaction!"

gdb log: http://pastie.org/10595344

**Comment by FedeDP** [comment]
Can this issue be reopened as it is not solved yet? Many thanks!
